[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="40xo8buq"
  NEXT_PUBLIC_SANITY_DATASET="production"
  SANITY_API_WRITE_TOKEN="Your Sanity API Write Token"
  SANITY_API_READ_TOKEN="Your Sanity API Read Token"