[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="40xo8buq"
  NEXT_PUBLIC_SANITY_DATASET="production"
  SANITY_API_WRITE_TOKEN="skqoPOVZUWSviEbmf8dPI82LJbwsxlsBZ9iVT8mEy8OlE02zFXe7GQXWw1nqhG8IWFi3vqcmXDExMUIAqh8mZnpDqzEoeaVyRWq2fseMvRdmUZ8oSgXTTRuAV9vRbzR7ZtDoOWMtQwJYYfXXMUq5FGi3MzZrDeAfG6pvMMpmJ0klVgmjoWkU"
  SANITY_API_READ_TOKEN="skiH178wC3qPtl9zNFInzKFzXIhWiScx0dBiLbeZsASpDWcaU9HY2RGK8E1HuKEo6xNRdBvt2a3jQpYLTyTrGIcWiyaxIbcpQmV68JNCxr7UZkPxTqmX0MjBC18FKBapmK9rbzg4SRPxM6lmH1xzKemDrt9KXgmzfEo4Qa0LhCgOjz8XcyeZ"